default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: acamargo
  password:

development:
  <<: *default
  database: db/bookmarks_development

test:
  <<: *default
  database: db/bookmarks_test

production:
  <<: *default
  database: db/bookmarks_production
